// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.trendmicro.mist.proto;

public final class MistMessage {
  private MistMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class KeyValuePair extends
      com.google.protobuf.GeneratedMessage {
    // Use KeyValuePair.newBuilder() to construct.
    private KeyValuePair() {}
    
    private static final KeyValuePair defaultInstance = new KeyValuePair();
    public static KeyValuePair getDefaultInstance() {
      return defaultInstance;
    }
    
    public KeyValuePair getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trendmicro.mist.proto.MistMessage.internal_static_com_trendmicro_mist_proto_KeyValuePair_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trendmicro.mist.proto.MistMessage.internal_static_com_trendmicro_mist_proto_KeyValuePair_fieldAccessorTable;
    }
    
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasValue) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasValue()) {
        output.writeString(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.trendmicro.mist.proto.MistMessage.KeyValuePair prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.trendmicro.mist.proto.MistMessage.KeyValuePair.newBuilder()
      private Builder() {}
      
      com.trendmicro.mist.proto.MistMessage.KeyValuePair result = new com.trendmicro.mist.proto.MistMessage.KeyValuePair();
      
      @Override
      protected com.trendmicro.mist.proto.MistMessage.KeyValuePair internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.trendmicro.mist.proto.MistMessage.KeyValuePair();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trendmicro.mist.proto.MistMessage.KeyValuePair.getDescriptor();
      }
      
      public com.trendmicro.mist.proto.MistMessage.KeyValuePair getDefaultInstanceForType() {
        return com.trendmicro.mist.proto.MistMessage.KeyValuePair.getDefaultInstance();
      }
      
      public com.trendmicro.mist.proto.MistMessage.KeyValuePair build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.trendmicro.mist.proto.MistMessage.KeyValuePair buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.trendmicro.mist.proto.MistMessage.KeyValuePair buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        com.trendmicro.mist.proto.MistMessage.KeyValuePair returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trendmicro.mist.proto.MistMessage.KeyValuePair) {
          return mergeFrom((com.trendmicro.mist.proto.MistMessage.KeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.trendmicro.mist.proto.MistMessage.KeyValuePair other) {
        if (other == com.trendmicro.mist.proto.MistMessage.KeyValuePair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = "";
        return this;
      }
      
      // required string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = "";
        return this;
      }
    }
    
    static {
      com.trendmicro.mist.proto.MistMessage.getDescriptor();
    }
  }
  
  public static final class MessageBlock extends
      com.google.protobuf.GeneratedMessage {
    // Use MessageBlock.newBuilder() to construct.
    private MessageBlock() {}
    
    private static final MessageBlock defaultInstance = new MessageBlock();
    public static MessageBlock getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageBlock getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trendmicro.mist.proto.MistMessage.internal_static_com_trendmicro_mist_proto_MessageBlock_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trendmicro.mist.proto.MistMessage.internal_static_com_trendmicro_mist_proto_MessageBlock_fieldAccessorTable;
    }
    
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private java.lang.String id_ = "";
    public boolean hasId() { return hasId; }
    public java.lang.String getId() { return id_; }
    
    // required bytes message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private boolean hasMessage;
    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessage() { return hasMessage; }
    public com.google.protobuf.ByteString getMessage() { return message_; }
    
    // optional int64 ttl = 3;
    public static final int TTL_FIELD_NUMBER = 3;
    private boolean hasTtl;
    private long ttl_ = 0L;
    public boolean hasTtl() { return hasTtl; }
    public long getTtl() { return ttl_; }
    
    // repeated .com.trendmicro.mist.proto.KeyValuePair properties = 4;
    public static final int PROPERTIES_FIELD_NUMBER = 4;
    private java.util.List<com.trendmicro.mist.proto.MistMessage.KeyValuePair> properties_ =
      java.util.Collections.emptyList();
    public java.util.List<com.trendmicro.mist.proto.MistMessage.KeyValuePair> getPropertiesList() {
      return properties_;
    }
    public int getPropertiesCount() { return properties_.size(); }
    public com.trendmicro.mist.proto.MistMessage.KeyValuePair getProperties(int index) {
      return properties_.get(index);
    }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasMessage) return false;
      for (com.trendmicro.mist.proto.MistMessage.KeyValuePair element : getPropertiesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeString(1, getId());
      }
      if (hasMessage()) {
        output.writeBytes(2, getMessage());
      }
      if (hasTtl()) {
        output.writeInt64(3, getTtl());
      }
      for (com.trendmicro.mist.proto.MistMessage.KeyValuePair element : getPropertiesList()) {
        output.writeMessage(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getId());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessage());
      }
      if (hasTtl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getTtl());
      }
      for (com.trendmicro.mist.proto.MistMessage.KeyValuePair element : getPropertiesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.trendmicro.mist.proto.MistMessage.MessageBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.trendmicro.mist.proto.MistMessage.MessageBlock prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.trendmicro.mist.proto.MistMessage.MessageBlock.newBuilder()
      private Builder() {}
      
      com.trendmicro.mist.proto.MistMessage.MessageBlock result = new com.trendmicro.mist.proto.MistMessage.MessageBlock();
      
      @Override
      protected com.trendmicro.mist.proto.MistMessage.MessageBlock internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.trendmicro.mist.proto.MistMessage.MessageBlock();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trendmicro.mist.proto.MistMessage.MessageBlock.getDescriptor();
      }
      
      public com.trendmicro.mist.proto.MistMessage.MessageBlock getDefaultInstanceForType() {
        return com.trendmicro.mist.proto.MistMessage.MessageBlock.getDefaultInstance();
      }
      
      public com.trendmicro.mist.proto.MistMessage.MessageBlock build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.trendmicro.mist.proto.MistMessage.MessageBlock buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.trendmicro.mist.proto.MistMessage.MessageBlock buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.properties_ != java.util.Collections.EMPTY_LIST) {
          result.properties_ =
            java.util.Collections.unmodifiableList(result.properties_);
        }
        com.trendmicro.mist.proto.MistMessage.MessageBlock returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trendmicro.mist.proto.MistMessage.MessageBlock) {
          return mergeFrom((com.trendmicro.mist.proto.MistMessage.MessageBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.trendmicro.mist.proto.MistMessage.MessageBlock other) {
        if (other == com.trendmicro.mist.proto.MistMessage.MessageBlock.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        if (!other.properties_.isEmpty()) {
          if (result.properties_.isEmpty()) {
            result.properties_ = new java.util.ArrayList<com.trendmicro.mist.proto.MistMessage.KeyValuePair>();
          }
          result.properties_.addAll(other.properties_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setId(input.readString());
              break;
            }
            case 18: {
              setMessage(input.readBytes());
              break;
            }
            case 24: {
              setTtl(input.readInt64());
              break;
            }
            case 34: {
              com.trendmicro.mist.proto.MistMessage.KeyValuePair.Builder subBuilder = com.trendmicro.mist.proto.MistMessage.KeyValuePair.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProperties(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public java.lang.String getId() {
        return result.getId();
      }
      public Builder setId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = "";
        return this;
      }
      
      // required bytes message = 2;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public com.google.protobuf.ByteString getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // optional int64 ttl = 3;
      public boolean hasTtl() {
        return result.hasTtl();
      }
      public long getTtl() {
        return result.getTtl();
      }
      public Builder setTtl(long value) {
        result.hasTtl = true;
        result.ttl_ = value;
        return this;
      }
      public Builder clearTtl() {
        result.hasTtl = false;
        result.ttl_ = 0L;
        return this;
      }
      
      // repeated .com.trendmicro.mist.proto.KeyValuePair properties = 4;
      public java.util.List<com.trendmicro.mist.proto.MistMessage.KeyValuePair> getPropertiesList() {
        return java.util.Collections.unmodifiableList(result.properties_);
      }
      public int getPropertiesCount() {
        return result.getPropertiesCount();
      }
      public com.trendmicro.mist.proto.MistMessage.KeyValuePair getProperties(int index) {
        return result.getProperties(index);
      }
      public Builder setProperties(int index, com.trendmicro.mist.proto.MistMessage.KeyValuePair value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.properties_.set(index, value);
        return this;
      }
      public Builder setProperties(int index, com.trendmicro.mist.proto.MistMessage.KeyValuePair.Builder builderForValue) {
        result.properties_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProperties(com.trendmicro.mist.proto.MistMessage.KeyValuePair value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.properties_.isEmpty()) {
          result.properties_ = new java.util.ArrayList<com.trendmicro.mist.proto.MistMessage.KeyValuePair>();
        }
        result.properties_.add(value);
        return this;
      }
      public Builder addProperties(com.trendmicro.mist.proto.MistMessage.KeyValuePair.Builder builderForValue) {
        if (result.properties_.isEmpty()) {
          result.properties_ = new java.util.ArrayList<com.trendmicro.mist.proto.MistMessage.KeyValuePair>();
        }
        result.properties_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProperties(
          java.lang.Iterable<? extends com.trendmicro.mist.proto.MistMessage.KeyValuePair> values) {
        if (result.properties_.isEmpty()) {
          result.properties_ = new java.util.ArrayList<com.trendmicro.mist.proto.MistMessage.KeyValuePair>();
        }
        super.addAll(values, result.properties_);
        return this;
      }
      public Builder clearProperties() {
        result.properties_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.trendmicro.mist.proto.MistMessage.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trendmicro_mist_proto_KeyValuePair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_trendmicro_mist_proto_KeyValuePair_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trendmicro_mist_proto_MessageBlock_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_trendmicro_mist_proto_MessageBlock_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\021MistMessage.proto\022\031com.trendmicro.mist" +
      ".proto\"*\n\014KeyValuePair\022\013\n\003key\030\001 \002(\t\022\r\n\005v" +
      "alue\030\002 \002(\t\"u\n\014MessageBlock\022\n\n\002id\030\001 \002(\t\022\017" +
      "\n\007message\030\002 \002(\014\022\013\n\003ttl\030\003 \001(\003\022;\n\nproperti" +
      "es\030\004 \003(\0132\'.com.trendmicro.mist.proto.Key" +
      "ValuePairB(\n\031com.trendmicro.mist.protoB\013" +
      "MistMessage";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_trendmicro_mist_proto_KeyValuePair_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_trendmicro_mist_proto_KeyValuePair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_trendmicro_mist_proto_KeyValuePair_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.trendmicro.mist.proto.MistMessage.KeyValuePair.class,
              com.trendmicro.mist.proto.MistMessage.KeyValuePair.Builder.class);
          internal_static_com_trendmicro_mist_proto_MessageBlock_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_trendmicro_mist_proto_MessageBlock_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_trendmicro_mist_proto_MessageBlock_descriptor,
              new java.lang.String[] { "Id", "Message", "Ttl", "Properties", },
              com.trendmicro.mist.proto.MistMessage.MessageBlock.class,
              com.trendmicro.mist.proto.MistMessage.MessageBlock.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
