source :rubygems

gem 'sinatra'
gem 'sinatra-contrib', :require => "sinatra/contrib"
gem 'sinatra-head', :require => "sinatra/head"

gem 'rack', "~> 1.3.5"
gem 'thin'

gem 'pow'
gem 'rrd-ffi', :require => "rrd"
gem 'i18n'
gem 'json'
gem 'builder'
gem 'coffee-script'
